load("//:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "solution1",
    srcs = ["Solution1.kt"],
    main_class = "me.brandonbuck.adventofcode.sonarsweep.Solution1Kt",
    deps = [
        "//2021/kotlin/me/brandonbuck/adventofcode/common:io",
    ],
)

kt_jvm_binary(
    name = "solution2",
    srcs = ["Solution2.kt"],
    main_class = "me.brandonbuck.adventofcode.sonarsweep.Solution2Kt",
    deps = [
        "//2021/kotlin/me/brandonbuck/adventofcode/common:io",
    ],
)
