load("//:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "solution1",
    srcs = ["Solution1.kt"],
    main_class = "me.brandonbuck.adventofcode.dive.Solution1Kt",
    deps = [
        "//2021/kotlin/me/brandonbuck/adventofcode/common:io",
    ],
)
